version: '3'

services:
  web:
    build: .
    command: npm run watch
    volumes:
      - .:/usr/node/app/
      - /usr/node/app/node_modules
    environment:
      - NODE_ENV=local
    ports:
      - "3000:3000"